# Generated by Django 5.2.3 on 2025-07-04 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0003_alter_route_destination_alter_route_source_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("row", "seat")},
        ),
    ]
