# Generated by Django 5.2.3 on 2025-07-04 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0004_alter_ticket_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("row", "seat", "flight")},
        ),
    ]
