# Generated by Django 5.2.3 on 2025-07-05 10:51

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0005_alter_ticket_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplane",
            name="image",
            field=models.ImageField(
                null=True, upload_to=airport.models.movie_image_file_path
            ),
        ),
    ]
